[build]
public_url = "/"

[watch]
watch = ["src/", "Cargo.toml", "Cargo.lock", "index.html", "css/", "tailwind.config.js"]

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "./css/styles.css", "-o", "./css/tailwind.css", "--minify"]
